# Generated by Django 4.2.5 on 2023-09-21 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='url',
        ),
        migrations.AddField(
            model_name='recipe',
            name='img',
            field=models.ImageField(default='n/a', upload_to=''),
            preserve_default=False,
        ),
    ]
